---
title: "Strain sharing rel. abundances across sites and ages"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
options(stringsAsFactors = FALSE)
```

## Prepare environment
```{r}
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(gridExtra)
library("reshape2")
library(magrittr)
library(data.table)
library(stringr)
library(viridis)
library(hrbrthemes)
```

## Load and manipulate metaphlan output
```{r}
#metaphlan output table
mpa_file <- read_delim("data/species_composition/milk_infant_samples_merged_abundance_contam_rm.txt", delim = '\t')

#separate full clade name into taxonomic levels
mpa_file.delim <- mpa_file %>% 
  tidyr::separate(clade_name, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species', 'Strain'), sep ='\\|', remove = FALSE, fill="right") 

#metadata table
metadata <- read_delim("data/metadata.csv", delim = ',')

#load and predominance groups information
bifido_groups <- read_delim("data/predominance_group/bifidos_groups.csv", delim = ',')
```

## Extract species information
```{r}
#select clades assigned to species level
mpa_file.clean.species <- mpa_file.delim %>% 
  filter(!is.na(Species) & is.na(Strain)) 

#keep simplified species name only
to.drop <- c("clade_name", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Strain")
mpa_file.species = mpa_file.clean.species[,!(names(mpa_file.clean.species) %in% to.drop)]
mpa_file.species$Species <- str_remove(mpa_file.species$Species, pattern = "s__")
mpa_file.species$Species <- gsub("_", " ", mpa_file.species$Species)

mpa_file.species.long <- mpa_file.species %>% 
  pivot_longer(cols = !Species, names_to = "Sample", values_to = "Abundance") 

#split sample ID for later merge with metadata table
mpa_file.species.long <- mpa_file.species.long %>% 
  mutate(full_ID=Sample) %>% 
  tidyr::separate(Sample, c('Sample', 'number'), sep ='_', remove = FALSE, fill="right") 

#metadata table
metadata <- metadata %>% select(-Correct_sample_name) 

#load and predominance groups information
metadata.full <- left_join(metadata, bifido_groups, by=c("Full_name"="Sample"))

#merge with metadata table
merged.species <- left_join(mpa_file.species.long, metadata.full, by=c("full_ID"="Full_name"))
merged.species.clean <- merged.species %>% 
   select(Species, Sample, Abundance, Sample_type, `Mother Infant Pair`, Gestational_diabetes_couple, Bodysite, Group) %>% 
  filter(Abundance>0) %>% 
  distinct()
```

# Species specific longitudinal abundances trajectories (suppl. figure 4B)

## Milk paired boxplot
```{r}
milk.to.milk.species <- merged.species.clean %>% 
  filter(Sample_type=="Milk_1M" |Sample_type=="Milk_3M") %>% 
  mutate(Timepoint= ifelse(Sample_type=="Milk_1M", "1", "3")) %>% 
  group_by(Species, `Mother Infant Pair`) %>% 
  mutate(n=n()) %>% 
  mutate(route="Milk2Milk") %>% 
  filter(n>1) %>% #both stool samples present 
  filter(Abundance<100) 

tmp.species.milk <- milk.to.milk.species %>%
  group_by(Species) %>%
  mutate(n_tmp=n()) %>% 
  select(Species, n_tmp) %>% 
  distinct() 

top.5species.milk <- tmp.species.milk[order(desc(tmp.species.milk$n_tmp)),] %>% 
  head(n=5) %>% 
  pull(Species)

milk.to.milk.species.top5 <-milk.to.milk.species %>% 
  filter(Species %in% top.5species.milk)

milk.pairedTrajectories <- ggplot(milk.to.milk.species.top5, aes(x=Sample_type, y=Abundance, fill=Sample_type)) +
  geom_boxplot() +
  geom_point()+
  theme_bw() +
  facet_wrap(~Species, ncol = 5) +
  geom_line(aes(group = `Mother Infant Pair`), size=0.5, color='gray40', alpha=0.3)+
  geom_point(aes(fill=Sample_type, group=`Mother Infant Pair`),size=1,shape=21)+
  scale_fill_manual(values=c("#e66101", "#fdb863")) 

pdf(file=paste0("figures/groups_stability/pairedDots_boxplots_top5milk.pdf"), width=8, height=3)
milk.pairedTrajectories
invisible(dev.off())

milk.pairedTrajectories
```

## Stool paired boxplot
```{r}

stool.to.stool.species <- merged.species.clean %>% 
  filter(Sample_type=="Stool_1M" |Sample_type=="Stool_6M") %>% 
  mutate(Timepoint= ifelse(Sample_type=="Stool_1M", "1", "6")) %>% 
  group_by(Species, `Mother Infant Pair`) %>% 
  mutate(n=n()) %>% 
  mutate(route="Stool2Stool") %>% 
  filter(n>1) %>% #both stool samples present 
  filter(Abundance<100) #avoid problematic samples with only one species detected

tmp.species.stool <- stool.to.stool.species %>%
  group_by(Species) %>%
  mutate(n_tmp=n()) %>% 
  select(Species, n_tmp) %>% 
  distinct() 

#top 10 most prevalent species across, present in both timepoints
top.10species.stool <- tmp.species.stool[order(desc(tmp.species.stool$n_tmp)),] %>% 
  head(n=10) %>% 
  pull(Species)

stool.to.stool.species.top10 <-stool.to.stool.species %>% 
  filter(Species %in% top.10species.stool)

stool.pairedTrajectories <- ggplot(stool.to.stool.species.top10, aes(x=Sample_type, y=Abundance, fill=Sample_type)) +
  geom_boxplot() +
  geom_point()+
  theme_bw() +
  facet_wrap(~Species, ncol = 5) +
  geom_line(aes(group = `Mother Infant Pair`), size=0.5, color='gray40', alpha=0.3)+
  geom_point(aes(fill=Sample_type, group=`Mother Infant Pair`),size=1,shape=21)+
  scale_fill_manual(values=c("#5e3c99", "#b2abd2")) 

pdf(file=paste0("figures/groups_stability/pairedDots_boxplots_top10stool.pdf"), width=8, height=6)
stool.pairedTrajectories
invisible(dev.off())

stool.pairedTrajectories
```

# Species persistence over time across predominance groups

## MILK TO MILK: divided by predominance group
```{r}
#get milk samples only from timeseries that have both timepoints
couples_bothMilk <- c(merged.species.clean %>% 
  filter(Bodysite=="Milk") %>% 
  select(`Mother Infant Pair`, Sample_type) %>% 
  distinct()%>% 
  group_by(`Mother Infant Pair`) %>% 
  summarise(n=n()) %>% 
  filter(n==2) %>% 
  pull(`Mother Infant Pair`))

#define transitions between same couple's milk samples from 1M -> 3M
merged.species.clean.milkBoth <- merged.species.clean %>% 
  filter(`Mother Infant Pair` %in% couples_bothMilk) %>% 
  filter(Bodysite=="Milk") %>% 
  select(`Mother Infant Pair`, Sample_type, Group) %>% 
  distinct() %>% 
  mutate(group_broad=ifelse(Group=="Group_4", "Other", "Bifidos")) %>% 
  select(-Group)

#write_csv2(merged.species.clean.milkBoth, "milkBoth_transitions.csv")
milk_trans <- read_csv("milkBoth_transitions.csv")

milk_trans %>% 
  group_by(Transition) %>% 
  summarise(n=n())

milk_trans.names <- milk_trans %>% 
  mutate(tmp=paste0(`Mother Infant Pair`, "_", Sample_type))

metadata.names <- metadata %>% 
  select(Old_sample_name,`Mother Infant Pair`, Sample_type) %>% 
  mutate(tmp=paste0(`Mother Infant Pair`, "_", Sample_type)) %>% 
  select(-`Mother Infant Pair`, -Sample_type)

milk_trans.names.full <- left_join(milk_trans.names, metadata.names, by="tmp")

milk_trans.names.full <- milk_trans.names.full %>% 
  select(Old_sample_name, Transition)

#merge with other data
merged.species.clean.milk.trans <- left_join(merged.species.clean, milk_trans.names.full, by=c("Sample"="Old_sample_name"))
merged.species.clean.milk.trans.clean <- merged.species.clean.milk.trans %>% 
  select(-Group, -Gestational_diabetes_couple) %>% 
  filter(!is.na(Transition)) %>% 
  mutate(Timepoint= ifelse(Sample_type=="Milk_1M", "1", "3")) %>% 
  filter(Abundance<100) #avoid problematic samples with only one species detected

tmp.species.milk.group <- merged.species.clean.milk.trans.clean %>%
  group_by(Species, Transition) %>%
  mutate(n_tmp=n()) %>% 
  select(Species, n_tmp, Transition) %>% 
  distinct() 

#top 10 most prevalent species across, present in both timepoints
top.species.milk.group <- tmp.species.milk.group[order(desc(tmp.species.milk.group$n_tmp)),] %>% 
  head(n=20) %>% 
  pull(Species)

merged.species.clean.milk.trans.clean.topSpecies <- merged.species.clean.milk.trans.clean %>% 
  filter(Species %in% top.species.milk.group)

mean.summary.milk.group <- merged.species.clean.milk.trans.clean.topSpecies %>% 
  group_by(Species, Timepoint, Transition) %>% 
  summarize(Mean = mean(Abundance, na.rm=TRUE)) %>% 
  group_by(Timepoint, Transition) %>% 
  mutate(tot= sum(Mean),
         percentage = Mean*100/tot)

mean.summary.milk.group$Timepoint <- as.numeric(mean.summary.milk.group$Timepoint)

species.presentinBothTimepoints <- mean.summary.milk.group %>% 
  select(Species, Timepoint, percentage)

species.presentin1timepointOnly <- species.presentinBothTimepoints %>% 
  group_by(Transition, Species) %>% 
  summarise(n=n()) %>% 
  filter(n==1) %>% 
  select(-n) %>% 
  mutate(Timepoint=case_when(
             (Transition=="Bifido2Bifido" & Species=="Staphylococcus epidermidis") ~ 1,
             (Transition=="Other2Bifido" & Species=="Cutibacterium acnes") ~ 3,
             (Transition=="Other2Bifido" & Species=="Escherichia coli") ~ 1,
             (Transition=="Other2Other" & Species=="Escherichia coli") ~ 3,
             (Transition=="Other2Other" & Species=="Cutibacterium acnes") ~ 3,
             (Transition=="Other2Other" & Species=="Klebsiella michiganensis") ~ 3,
             (Transition=="Bifido2Other" & Species=="Bifidobacterium bifidum") ~ 3,
             (Transition=="Bifido2Other" & Species=="Escherichia coli") ~ 3,
             (Transition=="Bifido2Other" & Species=="Phocaeicola vulgatus") ~ 3,
             TRUE ~ 0
           )) %>% 
    mutate(percentage=0)

species.presentin1timepointOnly$Timepoint <- as.numeric(species.presentin1timepointOnly$Timepoint)
species.presentinBothTimepoints$Timepoint <- as.numeric(species.presentinBothTimepoints$Timepoint)

all.combined <- rbind(species.presentinBothTimepoints, species.presentin1timepointOnly)

custom.milk1 <- c( "black", "green", "red", "blue", "#FFF176", "#FDD835", "#F9A825", "#FB8C00", "#EF6C00", "#D83415", "#BF360C", "#8D6E63", "#6D4C41", "#3E2723")

milk.persistence.plot <- ggplot(all.combined, aes(x=Timepoint, y=percentage, fill=Species)) + 
  geom_area(position = 'stack', alpha=0.9, size=.5, colour="black")+
  theme_light() +
  scale_fill_manual(values=rev(custom.milk1)) +
  labs(title = " (all) species present in both timepoints", x="Timepoint", y="Mean Relative Abundance (%)")+
  facet_grid(~Transition)

pdf(file=paste0("figures/groups_stability/milk_area_species_group_v2_FIXED-TRANSITIONS.pdf"), width=8, height=4)
milk.persistence.plot
invisible(dev.off())

milk.persistence.plot
```

## STOOL TO STOOL: divided by predominance group
```{r}
#get stool samples only from timeseries that have both timepoints
couples_bothStool <- c(merged.species.clean %>% 
  filter(Bodysite=="Stool") %>% 
  select(`Mother Infant Pair`, Sample_type) %>% 
  distinct()%>% 
  group_by(`Mother Infant Pair`) %>% 
  summarise(n=n()) %>% 
  filter(n==2) %>% 
  pull(`Mother Infant Pair`))

#define transitions between same couple's stool samples from 1M -> 6M
merged.species.clean.stoolBoth <- merged.species.clean %>% 
  filter(`Mother Infant Pair` %in% couples_bothStool) %>% 
  filter(Bodysite=="Stool") %>% 
  select(`Mother Infant Pair`, Sample_type, Group) %>% 
  distinct() %>% 
  mutate(group_broad=ifelse(Group=="Group_4", "Other", "Bifidos")) %>% 
  select(-Group)

#write_csv2(merged.species.clean.stoolBoth, "stoolBoth_transitions.csv")
stool_trans <- read_csv("stoolBoth_transitions.csv")

stool_trans %>% 
  group_by(Transition) %>% 
  summarise(n=n())

stool_trans.names <- stool_trans %>% 
  mutate(tmp=paste0(`Mother Infant Pair`, "_", Sample_type))

metadata.names <- metadata %>% 
  select(Old_sample_name,`Mother Infant Pair`, Sample_type) %>% 
  mutate(tmp=paste0(`Mother Infant Pair`, "_", Sample_type)) %>% 
  select(-`Mother Infant Pair`, -Sample_type)

stool_trans.names.full <- left_join(stool_trans.names, metadata.names, by="tmp")

stool_trans.names.full <- stool_trans.names.full %>% 
  select(Old_sample_name, Transition)

#merge with other data
merged.species.clean.stool.trans <- left_join(merged.species.clean, stool_trans.names.full, by=c("Sample"="Old_sample_name"))
merged.species.clean.stool.trans.clean <- merged.species.clean.stool.trans %>% 
  select(-Group, -Gestational_diabetes_couple) %>% 
  filter(!is.na(Transition)) %>% 
  mutate(Timepoint= ifelse(Sample_type=="Stool_1M", "1", "6")) %>% 
  filter(Abundance<100) #avoid problematic samples with only one species detected

tmp.species.stool.group <- merged.species.clean.stool.trans.clean %>%
  group_by(Species, Transition) %>%
  mutate(n_tmp=n()) %>% 
  select(Species, n_tmp, Transition) %>% 
  distinct() 

#top 10 most prevalent species across, present in both timepoints
top.species.stool.group <- tmp.species.stool.group[order(desc(tmp.species.stool.group$n_tmp)),] %>% 
  head(n=20) %>% 
  pull(Species)

merged.species.clean.stool.trans.clean.topSpecies <- merged.species.clean.stool.trans.clean %>% 
  filter(Species %in% top.species.stool.group)

mean.summary.stool.group <- merged.species.clean.stool.trans.clean.topSpecies %>% 
  group_by(Species, Timepoint, Transition) %>% 
  summarize(Mean = mean(Abundance, na.rm=TRUE)) %>% 
  group_by(Timepoint, Transition) %>% 
  mutate(tot= sum(Mean),
         percentage = Mean*100/tot)

mean.summary.stool.group$Timepoint <- as.numeric(mean.summary.stool.group$Timepoint)

species.stool.presentinBothTimepoints <- mean.summary.stool.group %>% 
  select(Species, Timepoint, percentage)

species.stool.presentinBothTimepoints$Timepoint <- as.numeric(species.stool.presentinBothTimepoints$Timepoint)

custom.stool3 <- c("#E57373", "#EC407A", "#D816B0", "#AB47BC", "#8E24AA", "#7E57C2", "#5E35B1", "#5C6BC0", "#3949AB", "#1A237E", "black", "white", "red", "blue", "green")

stool.persistence.plot <- ggplot(species.stool.presentinBothTimepoints, aes(x=Timepoint, y=percentage, fill=Species)) + 
  geom_area(position = 'stack', alpha=0.9, size=.5, colour="black")+
  theme_light() +
  scale_fill_manual(values=rev(custom.stool3)) +
  labs(title = " (all) species present in both timepoints", x="Timepoint", y="Mean Relative Abundance (%)")+
  facet_grid(~Transition)

pdf(file=paste0("figures/groups_stability/stool_area_species_group_v2_FIXED-TRANSITIONS.pdf"), width=8, height=4)
stool.persistence.plot
invisible(dev.off())

stool.persistence.plot
```
