---
title: "Secretor analysis on human breast milk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
options(stringsAsFactors = FALSE)
```


#Prepare environment.
```{r}
library(tidyverse)
library(ggplot2)
library(stringr)
library(circlize)
library(devtools)
library(ComplexHeatmap)
library(dendsort)

```

#load tables
```{r}

#metaphlan output table
mpa_file.milk <- read_delim("../../raw_data/master_metaphlan_subspecies_clean_milk.tsv", delim = '\t')

#metadata
metadata.master <- read_delim("../../metadata/metadata_complete_clean.csv", delim = ',')

metadata.master.clean <- metadata.master %>% 
  select(Sample_ID, Sample_type, Secretor_status_mother, Post_filtering_QC)

```

#maternal milk samples 1M only
```{r}
#separate full clade name into taxonomic levels
mpa_file.milk.delim <- mpa_file.milk %>% 
  tidyr::separate(clade_name, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species', 'Strain'), sep ='\\|', remove = FALSE, fill="right") 

#select clades assigned to species level
mpa_file.milk.clean.species <- mpa_file.milk.delim %>% 
  filter(!is.na(Species) & is.na(Strain)) 

#keep simplified species name only
to.drop <- c("clade_name", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Strain")
mpa_file.milk.species = mpa_file.milk.clean.species[,!(names(mpa_file.milk.clean.species) %in% to.drop)]
mpa_file.milk.species$Species <- str_remove(mpa_file.milk.species$Species, pattern = "s__")
mpa_file.milk.species$Species <- gsub("_", " ", mpa_file.milk.species$Species)

tmp.milk <- as.data.frame(mpa_file.milk.species %>% 
  remove_rownames %>% 
  column_to_rownames(var="Species") %>% 
  rowSums())

colnames(tmp.milk)[1] = "sum_abs"

mpa_file.milk.species.clean <- mpa_file.milk.species %>% 
  remove_rownames %>% 
  column_to_rownames(var="Species") 

#get columns metadata
colnames_ordered <- rownames_to_column(as.data.frame(t(mpa_file.milk.species.clean))) %>% 
  select(rowname)
  
colnames_ordered.metadata <- left_join(colnames_ordered, metadata.master.clean, by=c("rowname"="Sample_ID")) 

#get metadata and species rel abs in one table
mpa_file.milk.species.clean.t <- as.data.frame(t(mpa_file.milk.species.clean))
mpa_file.milk.species.clean.t <- mpa_file.milk.species.clean.t %>% 
  rownames_to_column("rowname")

merged.species <- left_join(colnames_ordered.metadata, mpa_file.milk.species.clean.t, by="rowname")

```

#calculate rel abundances for secretors
```{r}

merged.species.sec <- merged.species %>% 
  filter(Sample_type=="Milk_1M") %>% 
  filter(Secretor_status_mother==1) %>% 
  select(-Secretor_status_mother, -Sample_type, -rowname, -Post_filtering_QC)

merged.species.sec.t <- as.data.frame(t(merged.species.sec))

sec.tots <- merged.species.sec.t %>% 
  mutate(cum_relab=rowSums(.)) %>% 
  select(cum_relab) %>% 
  mutate(mean_relab=as.numeric(cum_relab)/as.numeric(dim(merged.species.sec)[1])) %>% 
  select(-cum_relab) %>% 
  rownames_to_column("Species")

sec.tots$mean_relab <- as.double(sec.tots$mean_relab)

top10.species <- sec.tots[order(desc(sec.tots$mean_relab)),] %>% 
  head(n=10) %>% 
  pull(Species)

sec.tots.top10 <- sec.tots %>% 
  filter(Species %in% top10.species) %>% 
  mutate(Status="Secretor") 

value_other_taxa <- as.numeric(100-sum(sec.tots.top10$mean_relab))

sec.tots.top10.complete <- sec.tots.top10 %>% 
  rbind(c("Other", value_other_taxa, "Secretor"))

```

#calculate rel abundances for NON secretors
```{r}

merged.species.nonsec <- merged.species %>% 
  filter(Sample_type=="Milk_1M") %>% 
  filter(Secretor_status_mother==0) %>% 
  select(-Secretor_status_mother, -Sample_type, -rowname, -Post_filtering_QC)

merged.species.nonsec.t <- as.data.frame(t(merged.species.nonsec))

nonsec.tots <- merged.species.nonsec.t %>% 
  mutate(cum_relab=rowSums(.)) %>% 
  select(cum_relab) %>% 
  mutate(mean_relab=as.numeric(cum_relab)/as.numeric(dim(merged.species.sec)[1])) %>% 
  select(-cum_relab) %>% 
  rownames_to_column("Species")

nonsec.tots$mean_relab <- as.double(nonsec.tots$mean_relab)

top10.species <- nonsec.tots[order(desc(nonsec.tots$mean_relab)),] %>% 
  head(n=10) %>% 
  pull(Species)

nonsec.tots.top10 <- nonsec.tots %>% 
  filter(Species %in% top10.species) %>% 
  mutate(Status="Non Secretor") 

value_other_taxa <- as.numeric(100-sum(nonsec.tots.top10$mean_relab))

nonsec.tots.top10.complete <- nonsec.tots.top10 %>% 
  rbind(c("Other", value_other_taxa, "Non Secretor"))

```

#merge secretor + non secretor tables
```{r}

metadata.milk.full.clean <- rbind(sec.tots.top10.complete, nonsec.tots.top10.complete)
metadata.milk.full.clean$mean_relab <- as.numeric(metadata.milk.full.clean$mean_relab)

#plot stacked barplot
ggplot(metadata.milk.full.clean, aes(fill=Species, y=mean_relab, x=Status)) + 
  geom_bar(position="fill", stat="identity")+
  theme_bw()

```


#heatmap
```{r, eval=FALSE}
#Set annotation
ann.milk <- data.frame(metadata.milk.full.clean$`Sample_type`, metadata.milk.full.clean$`Group`)
colnames(ann.milk) <- c('Sample_type', 'Group')

colours.milk <- list('Sample_type' = c('Milk_1M' = "#e66101", 'Milk_3M' = "#fdb863"),
  'Group' = c('Group_1' = '#630a4c', 'Group_2' = '#ad3691', 'Group_3' = '#de9ecd', 'Group_4' = '#f2e6ef'))

colAnn.milk <- HeatmapAnnotation(df = ann.milk,
  which = 'col',
  col = colours.milk,
  annotation_width = unit(c(1, 4), 'cm'),
  gap = unit(1, 'mm'))

col_fun.milk = colorRamp2(c(0, 0.01, 0.1, 1, 70, 100), 
                     c("white","#e5e8f2","#ccd1e6", "#6776b5", '#35499d', "#000000"))

#remove columns of samples that git discarded in post filtering QC
keep.samples.milk.list <- c(metadata.milk.full.clean %>% pull(rowname))

mpa_file.milk.species.clean.t.keepOnly <- rownames_to_column(as.data.frame(t(mpa_file.milk.species.clean))) %>% 
  filter(rowname %in% keep.samples.milk.list)

rownames(mpa_file.milk.species.clean.t.keepOnly) <- mpa_file.milk.species.clean.t.keepOnly[,1]
mpa_file.milk.species.clean.t.keepOnly.t <- as.data.frame(t(mpa_file.milk.species.clean.t.keepOnly %>% select(-rowname)))

mpa.milk.mat <- as.matrix(mpa_file.milk.species.clean.t.keepOnly.t)
row_dend.milk = dendsort(hclust(dist(mpa.milk.mat)))
col_dend.milk = dendsort(hclust(dist(t(mpa.milk.mat))))

#plot heatmap milk
heat.milk <- Heatmap(mpa.milk.mat, 
        name = "Abundance", 
        cluster_columns = col_dend.milk,
        clustering_distance_rows = "euclidean", 
        clustering_distance_columns = "euclidean",
        show_column_names = FALSE, 
        show_row_dend = FALSE, 
        col = col_fun.milk, 
        row_names_gp = gpar(fontsize = 8),
        top_annotation=colAnn.milk, 
        column_dend_height = unit(5, "mm"))

pdf(file=paste0("figures/heatmap_Milk_vert.pdf"), width=9, height=3.5)
heat.milk
dev.off()

heat.milk
```
