---
title: "Heatmap of the taxonomic composition of milk and infant stool samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
options(stringsAsFactors = FALSE)
```


#Prepare environment.
```{r}
library(tidyverse)
library(ggplot2)
library(stringr)
library(circlize)
library(devtools)
library(ComplexHeatmap)
library(dendsort)
```

#Load tables
```{r}
#stool 
mpa_file.stool <- read_delim("data/species_composition/infant_rel_abundance_contam_rm_keepOnly.txt", delim = '\t')
#milk
mpa_file.milk <- read_delim("data/species_composition/milk_rel_abundance_contam_rm_keepOnly.txt", delim = '\t')
#predominant group metadata
bifido_groups <- read_delim("data/predominance_group/bifidos_groups.csv", delim = ',')
#metadata
metadata.master <- read_delim("data/metadata_complete.csv", delim = ',')
```

#Heatmap for infant stool samples
```{r}
#separate full clade name into taxonomic levels
mpa_file.stool.delim <- mpa_file.stool %>% 
  tidyr::separate(clade_name, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species', 'Strain'), sep ='\\|', remove = FALSE, fill="right") 

#select clades assigned to species level
mpa_file.stool.clean.species <- mpa_file.stool.delim %>% 
  filter(!is.na(Species) & is.na(Strain)) 

#keep simplified species name only
to.drop <- c("clade_name", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Strain")
mpa_file.stool.species = mpa_file.stool.clean.species[,!(names(mpa_file.stool.clean.species) %in% to.drop)]
mpa_file.stool.species$Species <- str_remove(mpa_file.stool.species$Species, pattern = "s__")
mpa_file.stool.species$Species <- gsub("_", " ", mpa_file.stool.species$Species)

tmp <- as.data.frame(mpa_file.stool.species %>% 
  remove_rownames %>% 
  column_to_rownames(var="Species") %>% 
  rowSums())

colnames(tmp)[1] = "sum_abs"

#define top species to show in heatmap
species_to_keep <- tmp %>% 
  arrange(sum_abs) %>% 
  top_n(15) 

species_to_keep$Species <- rownames(species_to_keep)

species_to_keep.list <- c(species_to_keep %>% 
                                  select(Species) %>% pull())

mpa_file.stool.species.clean <- mpa_file.stool.species %>% 
 filter(Species %in% species_to_keep.list) %>% 
  remove_rownames %>% 
  column_to_rownames(var="Species") 

#get columns metadata
colnames_ordered.stool <- rownames_to_column(as.data.frame(t(mpa_file.stool.species.clean))) %>% 
  select(rowname)
  
colnames_ordered.stool.metadata <- left_join(colnames_ordered.stool, metadata.master, by=c("rowname"="Old_sample_name")) 

#add info bifido groups
metadata.stool.full <- left_join(colnames_ordered.stool.metadata, bifido_groups, by=c("Full_name"="Sample"))

#discard samples that did not pass post-filtering QC
metadata.stool.full.clean <- metadata.stool.full %>% 
  filter(`Post_filtering_QC`=="Keep") %>% 
  mutate(Delivery_mode_vag=ifelse(Delivery_mode_cat1=="AVD" | Delivery_mode_cat1=="SVD", "Yes", "No"))

#Set annotation
ann.stool <- data.frame(metadata.stool.full.clean$`Sample_type`, 
                  metadata.stool.full.clean$`Delivery_mode_vag`, 
                  metadata.stool.full.clean$`Exclusive_bf`,
                 metadata.stool.full.clean$`Abx_exposure_any`,
                 metadata.stool.full.clean$`Group`)

colnames(ann.stool) <- c('Sample_type', 'Delivery_mode_vag','Exclusive_bf', 
                   'Abx_exposure_any', 'Group')

colours.stool <- list('Sample_type' = c('Stool_1M' = "#5e3c99", 'Stool_6M' = "#b2abd2"),
  'Delivery_mode_vag' = c('Yes' = 'black', 'No' = 'cornflowerblue'),
  'Exclusive_bf' = c('Yes' = 'black', 'No' = 'cornflowerblue'),
  'Abx_exposure_any' = c('Yes' = 'black', 'No' = 'cornflowerblue'),
  'Group' = c('Group_1' = '#630a4c', 'Group_2' = '#ad3691', 'Group_3' = '#de9ecd', 'Group_4' = '#f2e6ef'))

colAnn.stool <- HeatmapAnnotation(df = ann.stool,
  which = 'col',
  col = colours.stool,
  annotation_width = unit(c(0.1, 0.1), 'cm'),
  gap = unit(0.5, 'mm'))


col_fun = colorRamp2(c(0, 0.01, 0.1, 1, 70, 100), 
                     c("white","#e5e8f2","#ccd1e6", "#6776b5", '#35499d', "#000000"))

#remove columns of samples that git discarded in post filtering QC
keep.samples.stool.list <- c(metadata.stool.full.clean %>% pull(rowname))

mpa_file.stool.species.clean.t.keepOnly <- rownames_to_column(as.data.frame(t(mpa_file.stool.species.clean))) %>% 
  filter(rowname %in% keep.samples.stool.list)

rownames(mpa_file.stool.species.clean.t.keepOnly) <- mpa_file.stool.species.clean.t.keepOnly[,1]
mpa_file.stool.species.clean.t.keepOnly.t <- as.data.frame(t(mpa_file.stool.species.clean.t.keepOnly %>% select(-rowname)))

mpa.stool.mat <- as.matrix(mpa_file.stool.species.clean.t.keepOnly.t)
row_dend.stool = dendsort(hclust(dist(mpa.stool.mat)))
col_dend.stool = dendsort(hclust(dist(t(mpa.stool.mat))))

#plot heatmap stool samples
heat.stool <- Heatmap(mpa.stool.mat, 
        name = "Abundance", 
        cluster_columns = col_dend.stool,
        clustering_distance_rows = "euclidean", 
        clustering_distance_columns = "euclidean",
        show_column_names = FALSE, 
        show_row_dend = FALSE, 
        col = col_fun, 
        row_names_gp = gpar(fontsize = 8),
        top_annotation=colAnn.stool, 
        column_dend_height = unit(5, "mm"))

pdf(file=paste0("figures/species_composition/heatmap_Stool_vert.pdf"), width=10, height=5.5)
heat.stool
invisible(dev.off())

heat.stool
```

#Heatmap for maternal milk samples
```{r}
#separate full clade name into taxonomic levels
mpa_file.milk.delim <- mpa_file.milk %>% 
  tidyr::separate(clade_name, c('Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species', 'Strain'), sep ='\\|', remove = FALSE, fill="right") 

#select clades assigned to species level
mpa_file.milk.clean.species <- mpa_file.milk.delim %>% 
  filter(!is.na(Species) & is.na(Strain)) 

#keep simplified species name only
to.drop <- c("clade_name", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Strain")
mpa_file.milk.species = mpa_file.milk.clean.species[,!(names(mpa_file.milk.clean.species) %in% to.drop)]
mpa_file.milk.species$Species <- str_remove(mpa_file.milk.species$Species, pattern = "s__")
mpa_file.milk.species$Species <- gsub("_", " ", mpa_file.milk.species$Species)

tmp.milk <- as.data.frame(mpa_file.milk.species %>% 
  remove_rownames %>% 
  column_to_rownames(var="Species") %>% 
  rowSums())

colnames(tmp.milk)[1] = "sum_abs"

species_to_keep.milk <- tmp.milk %>% 
  arrange(sum_abs) %>% 
  top_n(15) 

species_to_keep.milk$Species <- rownames(species_to_keep.milk)

species_to_keep.milk.list <- c(species_to_keep.milk %>% 
                                 select(Species) %>% 
                                 pull())

mpa_file.milk.species.clean <- mpa_file.milk.species %>% 
 filter(Species %in% species_to_keep.milk.list) %>% 
  remove_rownames %>% 
  column_to_rownames(var="Species") 

#get columns metadata
colnames_ordered <- rownames_to_column(as.data.frame(t(mpa_file.milk.species.clean))) %>% 
  select(rowname)
  
colnames_ordered.metadata <- left_join(colnames_ordered, metadata.master, by=c("rowname"="Old_sample_name")) 

#add info bifido groups
metadata.milk.full <- left_join(colnames_ordered.metadata, bifido_groups, by=c("Full_name"="Sample"))

#discard samples that did not pass post-filtering QC
metadata.milk.full.clean <- metadata.milk.full %>% 
  filter(`Post_filtering_QC`=="Keep")

#Set annotation
ann.milk <- data.frame(metadata.milk.full.clean$`Sample_type`, metadata.milk.full.clean$`Group`)
colnames(ann.milk) <- c('Sample_type', 'Group')

colours.milk <- list('Sample_type' = c('Milk_1M' = "#e66101", 'Milk_3M' = "#fdb863"),
  'Group' = c('Group_1' = '#630a4c', 'Group_2' = '#ad3691', 'Group_3' = '#de9ecd', 'Group_4' = '#f2e6ef'))

colAnn.milk <- HeatmapAnnotation(df = ann.milk,
  which = 'col',
  col = colours.milk,
  annotation_width = unit(c(1, 4), 'cm'),
  gap = unit(1, 'mm'))

col_fun.milk = colorRamp2(c(0, 0.01, 0.1, 1, 70, 100), 
                     c("white","#e5e8f2","#ccd1e6", "#6776b5", '#35499d', "#000000"))

#remove columns of samples that git discarded in post filtering QC
keep.samples.milk.list <- c(metadata.milk.full.clean %>% pull(rowname))

mpa_file.milk.species.clean.t.keepOnly <- rownames_to_column(as.data.frame(t(mpa_file.milk.species.clean))) %>% 
  filter(rowname %in% keep.samples.milk.list)

rownames(mpa_file.milk.species.clean.t.keepOnly) <- mpa_file.milk.species.clean.t.keepOnly[,1]
mpa_file.milk.species.clean.t.keepOnly.t <- as.data.frame(t(mpa_file.milk.species.clean.t.keepOnly %>% select(-rowname)))

mpa.milk.mat <- as.matrix(mpa_file.milk.species.clean.t.keepOnly.t)
row_dend.milk = dendsort(hclust(dist(mpa.milk.mat)))
col_dend.milk = dendsort(hclust(dist(t(mpa.milk.mat))))

#plot heatmap milk
heat.milk <- Heatmap(mpa.milk.mat, 
        name = "Abundance", 
        cluster_columns = col_dend.milk,
        clustering_distance_rows = "euclidean", 
        clustering_distance_columns = "euclidean",
        show_column_names = FALSE, 
        show_row_dend = FALSE, 
        col = col_fun.milk, 
        row_names_gp = gpar(fontsize = 8),
        top_annotation=colAnn.milk, 
        column_dend_height = unit(5, "mm"))

pdf(file=paste0("figures/species_composition/heatmap_Milk_vert.pdf"), width=9, height=3.5)
heat.milk
invisible(dev.off())

heat.milk
```
