---
title: "Alpha diversity - Shannon index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
options(stringsAsFactors = FALSE)
```

## Prepare environment
```{r}
library(tidyverse)
library(ggpubr)
library(ggplot2)
```

## Load tables
```{r}
#shannon
shannon_file <- read_delim("data/alpha_diversity/Milk_Stool_ONLY_count_contam_rm_shannon.tsv", delim = '\t')
#richness
richness_file <- read_delim("data/alpha_diversity/Milk_Stool_ONLY_count_contam_rm_richness.tsv", delim = '\t')
#richness
simpson_file <- read_delim("data/alpha_diversity/Milk_Stool_ONLY_count_contam_rm_simpson.tsv", delim = '\t')
#metadata table
metadata <- read_delim("data/metadata.csv", delim = ',')
```

## Plot Shannon diversity 
```{r}
shannon_file.meta <- left_join(shannon_file, metadata, by=c("Sample_clean"="Full_name")) %>% filter(!is.na(Sample_type))

shannon.plot <- ggplot(data = shannon_file.meta, 
       mapping = aes(x = Sample_type, y = diversity_shannon, fill = Sample_type)) +
    geom_boxplot(outlier.size = -1) +
    scale_fill_manual(values=c("#e66101", "#fdb863", "#5e3c99", "#b2abd2")) +
    theme_bw() +
    theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (10)), 
          strip.background = element_rect(color="white", fill="white"), 
          axis.title.x = element_text(size= 10),
          axis.title.y = element_text(size= 10)) 


my_comparisons <- list(c("Milk_1M", "Milk_3M"), c("Stool_1M", "Stool_6M"), c("Milk_3M", "Stool_1M"))
shannon.plot + stat_compare_means(method = "t.test", label = "p.signif",
                       comparisons=my_comparisons, paired=TRUE)

pdf(file=paste0("figures/alpha_diversity/shannon.plot_new.pdf"), width=5, height=5)
shannon.plot
invisible(dev.off())
```